# Config file for [Air] in TOML format for the User Service

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command to run the Flask app.
# You could replace this with a custom command to run your app.
cmd = "flask run"
# Customize the binary, can setup environment variables when running your app.
full_bin = "FLASK_ENV=development FLASK_APP=app.py flask run"
# Watch these filename extensions.
include_ext = ["py", "html", "css", "js"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "venv", "node_modules"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# Exclude specific regular expressions.
exclude_regex = ["_test\\.py", "test_.*"]
# Exclude unchanged files.
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = 500 # ms
# Add additional arguments when running binary (bin/full_bin). 
args_bin = []

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
