version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    command: flask run --host=0.0.0.0
    depends_on:
      - db
      - rabbitmq

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-users'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
  rabbitmq-data:
  rabbitmq-log:
