name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ORGA_NAME: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Vérifier que le secret LOGINDOCKER est valide
      run: |
        if [ -z "${{ secrets.LOGINDOCKER }}" ]; then
          echo "Erreur : le secret LOGINDOCKER est vide"
          exit 1
        else
          echo "Le secret LOGINDOCKER est valide"
        fi


    - name: Log in to GitHub Container Registry
      run: |
        echo ${{ secrets.LOGINDOCKER }} | docker login ghcr.io -u ${{ secrets.USER }} --password-stdin


    - name: Build Docker Image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.ORGA_NAME }}/${{ env.IMAGE_NAME }}:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.ORGA_NAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to server
      run: |
        echo "Deploying application..."
        # Commandes de déploiement spécifiques (ex. SSH, Kubernetes)
